### ISSUE TITLE
Stripe, reCAPTCHA, and mobile issues

### ISSUE THREAD

**Issue by matt-sanders** [Charitable/Charitable-reCAPTCHA#1]
Hey guys

We've just run into an issue where if a user makes a donation using stripe on a mobile phone the process fails. The wheel just spins and nothing happens, no PHP errors are logged either.

Steps to replicate:

1. Create a new wordpress install
2. Install Charitable latest version
3. Install Charitable Stripe latest version
4. Install Charitable reCAPTCHA latest version
5. Add keys to reCAPTCHA settings
6. Enable Stripe payment gateway, add keys, set to test mode
7. Create a new campaign, leave everything as default ( e.g. unlimited price etc )
8. Open a chrome private browsing window
9. Open dev tools and toggle the device toolbar
10. Set the device/screen size to "iPhone 6/7/8"
11. Navigate to your recently created campaign and make a donation
12. Fill out donation form, enter test stripe credit card details
13. You should be prompted with a reCAPTCHA test ( hence the private browsing window )
14. Complete the verification, the "donate" button should now be a spinning wheel that never stops spinning and never submits the form
15. No donation is made, no stripe transactions are submitted

Let me know if you need any more information.
Thanks heaps!

**Comment by matt-sanders** [comment]
Hey guys, any progress here?

**Comment by ericnicolaas** [comment]
I've been able to identify the issue here. Specifically it has to do with the way Charitable is handling pending processes. When you have Stripe & reCAPTCHA running at the same time, there are two pending processes which need to be resolved before the donation form is submitted — first is the Stripe tokenization of the card data, and second is the reCAPTCHA validation. 

The problem here is that the way we're removing these pending processes is not taking into account that they may be completed in a different order than they were started in. The result is that Charitable thinks the reCAPTCHA validation is never done, though in fact it is. 

Should have a fix soon, possibly a combination of an update to Charitable reCAPTCHA and the core plugin itself as well.

**Comment by matt-sanders** [comment]
@ericnicolaas thanks for the updates, I seem to still be having issues though. See a demo link [here](https://donationtest.wpengine.com/campaigns/test-campaign/donate/) the htauth details are username: demo password: donate2019 Stripe is in test mode so you can use any cards from [here](https://stripe.com/docs/testing#international-cards) when I get through the reCAPTCHA I still get the spinning wheel and an error in the console: `anchor:1 Uncaught (in promise) null`. reCAPTCHA is V2 invisible. let me know if you need admin logins and I can get them to you.

This is also happening on my local machine, so it's not an issue with the htauth layer.
